### ISSUE TITLE
Could you contribute to Tomcat's RemoteIpValve?

### ISSUE THREAD

**Issue by stokito** [qaware/x-forwarded-filter#3]
Hi @Michael-Frank 

You made a great job, thank you. Unfortunately I can't use your filter and I need to use Tomcat's RemoteIpValve. What I especially need is to populate request.serverName from X-Forwarded-Host.
And I found a ticket with a patch in [Bug 57665 - support x-forwarded-host](https://bz.apache.org/bugzilla/show_bug.cgi?id=57665)
There in comment I described my situation and why I can't use your filter.
I checked that patch and code of whole RemoteIpValve and I think it can be significantly improved.
At least it would be great if it can support `Forwarded` header.

Unfortunately ATM I don't enough time to send to Tomcat a new patch but first of all I would like to ask you to contribute as a person who knows better how to implement this.

Can you help with this? 
Thank you in advance

**Comment by Michael-Frank** [comment]
Hi Sergey,
Thanks :smiley:  
I see we have a similar use-case with migrating legacy apps. :grin: 

Regarding your problem:
To my knowledge, filters are registered and executed according to the order they are specified in web.xml.
Is it an option for your users to specify the filter in their own web.xml instead of  `$CATALINA_BASE/conf/web.xml` ? Thats the way we did it for our users.

If that does not work for you, there seams to be another option: implement the filter as a [Tomcat ValveComponent](http://tomcat.apache.org/tomcat-8.0-doc/config/valve.html)
```java
import org.apache.catalina.valves.ValveBase;
public class MyXForwardedValve extends ValveBase {
    @Override
    public void invoke(Request request, Response response) throws IOException, ServletException {
        // x-forwarded processing here ..
        getNext().invoke(request, response);
    }
}
```
register it as follows in server.xml:
`<Valve className="de.example.MyXForwardedValve" />`

Contributing to Tomcat is a good idea and appealing. But they appear to be unwilling to make any movement in that direction - as every other major servlet engine. Hence why this filter exists in the first place.
I will evaluate if its worth investing time.

**Comment by stokito** [comment]
Hi and thank you for reply. Yes, I thought about implementing a custom Valve but then decided just to use Tomcat's patched RemoteIpValve while it fits out needs.
Then let's wait while someone answers on my comment to Bug 57665 - support x-forwarded-host.
Until that situation is unclear. I'll ping you back with updates. Now I'll close the ticket as resolved/won't fix if any objections

**Comment by Michael-Frank** [comment]
I am fine with that approach. Lets see how willing the Tomcat guys are regarding that motion.

**Comment by Michael-Frank** [comment]
looks like the tomcat guys are still playing dead

**Comment by stokito** [comment]
Yeah, but could you leave a comment there to ping them?
https://bz.apache.org/bugzilla/show_bug.cgi?id=57665#add_comment

**Comment by Michael-Frank** [comment]
@stokito
Update:   [Tomacat Bug 57665 - support x-forwarded-host](https://bz.apache.org/bugzilla/show_bug.cgi?id=57665) was finally merged
Fixed in:
- master for 9.0.23 onwards
- 8.5.x for 8.5.44 onwards
- 7.0.x for 7.0.97 onwards

**Comment by stokito** [comment]
@Michael-Frank thank you!
